### ISSUE TITLE
mina/rails should not be required

### ISSUE THREAD

**Issue by Juanmcuello** [scarfacedeb/mina-unicorn#23]
I use mina and mina-unicorn, but I don't use rails. When using mina, if you don't use rails, you simply not require `mina/rails` and that's it. But if you require `mina/unicorn` in the mina `deploy.rb`, mina-unicorn requires `mina/rails` (See [this line](https://github.com/scarfacedeb/mina-unicorn/blob/master/lib/mina/unicorn/tasks.rb#L2)) and you end up with with vars like `shared_dirs` including rails paths that aren't needed (and could create other conflicts).

I think mina-unicorn should not require `mina/rails` and `unicorn_env`, which uses `rails_env` should be explicitly set. 

@scarfacedeb , what do you think? I can create a PR if you agree with the changes.

**Comment by Juanmcuello** [comment]
@scarfacedeb , any thoughts?

**Comment by scarfacedeb** [comment]
You're agree, it won't hurt to have less implicit requires in the gem.

But I don't want to break it for all of the other users that rely on implicit default value of `unicorn_env`.

I think that the best way to deal with it is to remove require and check if `rails_env` has been already set. And if that's the case, it should work as before. Otherwise, setting it to `deployment` seems like a decent default value.

**Comment by scarfacedeb** [comment]
Continue in #24
